### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by jeroenrinzema** [sysco-middleware/cp-schema-registry-ui#1]
A way needs to be created that allows us to create notifications in a easy way using the [Spectre toasts component](https://picturepan2.github.io/spectre/components.html#toasts).

Ideally would a function/object be added to the [Vue instance](https://vuejs.org/v2/cookbook/adding-instance-properties.html).

A notification could be a warning/success/error.

## Example

```javascript
new Vue({
  mounted: function() {
    this.$notification.success('Vue is mounted!')
    this.$notification.error('Something went terribly wrong')
  }
})
```

**Comment by NikitaZhevnitskiy** [comment]
Does user needs to allow notifications in browser?

**Comment by jeroenrinzema** [comment]
No a notification is a small popup in the bottom right corner

<img width="836" alt="screen shot 2018-06-04 at 18 46 53" src="https://user-images.githubusercontent.com/3440116/40930365-cd931042-6827-11e8-8657-5a574bdee8f4.png">
